Feature Header
mqasimdilshad1/MegaMart pull request #2
Opened 2023-11-24 14:42 UTC by mqasimdilshad1

The header now adapts more effectively to different screen sizes, ensuring a seamless user experience on various devices.

2023-11-24 15:42 UTC, naumanzchaudhry requested changes

2023-11-24 15:42 UTC, naumanzchaudhry commented on public/index.html
> +      content="Web site created using create-react-app"
Write useful descriptions

2023-11-24 15:42 UTC, naumanzchaudhry commented on public/index.html
> +<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
Check what this `preconnect` does

2023-11-24 15:42 UTC, naumanzchaudhry commented on public/index.html
> +    <title>React App</title>
First thing you do in a project if you create project using some tool. You cleanup any dummy titles data to make changes according to your project

2023-11-24 15:42 UTC, naumanzchaudhry commented on public/index.html
> +    <div id="root"></div>
What happens when this id is changed? Will the app work?

2023-11-24 15:42 UTC, naumanzchaudhry commented on public/manifest.json
> +  "short_name": "React App",
Useful data should be there

2023-11-24 15:42 UTC, naumanzchaudhry commented on src/Components/Header.js
> +        <img src="./icons/megamart.svg" alt="megamart" />
Check what are the other methods to add images?

2023-11-24 15:42 UTC, naumanzchaudhry commented on src/Components/SearchBar.js
> +            <option onClick={() => handleCategorySelect("Mobiles")}>
Let's say you have 1000 categories to show & select? This method of writing all of them using this method would be cumbersome. You can put the categories in an array and loop the option tag

2023-11-24 15:42 UTC, naumanzchaudhry commented on src/styles.css
> +  --blue: #008ecc;
These names should be a little bit better. I think this blue colour is your primary colour. They should be named as such. Consult @MuaviyaImran on this!

2023-11-24 15:42 UTC, naumanzchaudhry commented on src/styles.css
> +    padding: 0;
Setup code formatting in your VSCode. On save you can format files automatically. Which makes it easier for everyone else.

2023-11-24 15:42 UTC, naumanzchaudhry commented
PR titles should be Title Cased. Please edit that. 

+1 for writing PR description!

2023-11-24 16:37 UTC, mqasimdilshad1 commented on public/index.html
> +      content="Web site created using create-react-app"
done

2023-11-24 17:01 UTC, mqasimdilshad1 commented on public/index.html
> +    <div id="root"></div>
As I read this div with id = root is the mounting point of our react application. if we change the id to something else the app could cause problem because React uses this div to render and manage the application. If we change the id attribute than we also need to update our JavaScript code where the React application is initialized to use the correct ID.
ReactDOM.render(
    <App />
  document.getElementById('root')
);

2023-11-24 17:14 UTC, mqasimdilshad1 commented on src/Components/Header.js
> +        <img src="./icons/megamart.svg" alt="megamart" />
1. Using the <picture> Element
    The <picture> element allows us to define multiple sources for an image based on different conditions.
    This allows the browser to choose the most suitable source based on factors like screen size, resolution, and image 
    format support. The <picture> element is commonly used when we want to deliver different image versions.
2. CSS Background Image
    we can use CSS to set a background image for an element.
3. Inline SVG

2023-11-24 17:29 UTC, mqasimdilshad1 commented on src/Components/SearchBar.js
> +            <option onClick={() => handleCategorySelect("Mobiles")}>
yes this one is much better solution i am working on it.

2023-11-25 06:47 UTC, mqasimdilshad1 commented on public/index.html
> +<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
link rel="preconnect" in our HTML allows us to give the browser a hint that it should start setting up connections to specific domains early, optimizing the loading process in our case its getting font from google font  api.

2023-11-26 12:55 UTC, MuaviyaImran commented on src/index.js
> +    <App />
use formatter  (Like "Prettier" or something else)

2023-11-26 12:58 UTC, MuaviyaImran commented on src/styles.css
> +.cart-detail {
if your are using flex, for its children use flex-gap instead of padding or margin in order to allocate spacing between children

2023-11-26 12:59 UTC, MuaviyaImran commented on src/Components/Header.js
> +        <img src="./icons/megamart.svg" alt="megamart" />
try to use Title case in "img alt"

2024-02-21 17:36 UTC, merged